targets:
  $default:
    builders:
      summer_generator|summer:
        enabled: true

builders:

  summerBuilder:
    target: ":summer_generator"
    import: "package:summer_generator/summer_generator.dart"
    builder_factories: [ "summerBuilder" ]
    build_extensions: {"$lib$": ["generated/summer.dart"]}
    auto_apply: all_packages
    build_to: source
